backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Página Principal"
    files:
      - name: "contenido"
        label: "Contenido Home"
        file: "src/content/home.json"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
